backfill:
  fields:
    start_date:
      required: true
      example: "2024-01-01"
      selector:
        date:
    end_date:
      required: false
      example: "2024-12-31"
      selector:
        date:
